### ISSUE TITLE
Add Header to all types

### ISSUE THREAD

**Issue by csherstan** [ros/std_msgs#7]
I find myself often needing to create wrapper messages types that just add a Header field to the other std_msgs. The purpose being to allow to synchronize various events.

Here's one example: I use algorithms that make temporally extended predictions, say predicting the motor speed 10 timesteps in the future. Now I want to keep an error measure of my predictions, but obviously I don't know the error until 10 timesteps have passed. I need to mark the errors I'm publishing with the same seq and/or timestamp as the predictions that I publish so that I can later synchronize them.

It would be handy if Header was added to the definition of all message types.

If that doesn't make sense I would love to know why. Perhaps I'm doing something wrong?

**Comment by dirk-thomas** [comment]
You should create a custom message for your use case with a specific semantic meaning rather then using a generic `Int32Stamped` / `Float32Stamped` (if it would exist).

**Comment by csherstan** [comment]
Which is what I'm doing. But wouldn't it make sense to create Stamped versions of all the std_msgs?

A quick search shows that I'm not the only one who's ever run into this: https://github.com/aginika/aginika-pcl-ros/blob/master/msg/Int32Stamped.msg
http://docs.ros.org/groovy/api/jsk_pcl_ros/html/msg/Int32Stamped.html

**Comment by chadrockey** [comment]
@csherstan see more information in these ros-users threads from a while back.

http://answers.ros.org/question/9715/stamped-std_msgs/

http://ros-users.122217.n3.nabble.com/sensor-msgs-Low-Cost-Android-review-tp4019140p4019163.html

"This is convenient, but there are a few problems with this approach.  First, with common_msgs, we try to make data as standardized as possible.  This is so that any dataset could be a reference dataset for another institution and that that all messages "stand alone".  See this great answer by Ken Conley on why "stamped" std_msgs do not exist:
http://answers.ros.org/question/9715/stamped-std_msgs/

One of the most important things for processing quantitative information is the unit of measure.  It's important to define a well documented message in order to standardize units.  Besides the obvious (using arcane units like 'foot-candle' instead of lux for illuminance: http://en.wikipedia.org/wiki/Foot-candle), there can be issues with SI units as well.  For instance, most people (and hardware) work more with Celsius rather than Kelvin.  Kelvin is most important for absolute energy and entropy calculations.  ROS REP 103 (http://www.ros.org/reps/rep-0103.html) suggests the use of SI base units (Kelvin) and SI derived units (Celsius).  It just so happens that most modern electronics tend to operate somewhere between 0C and 100C before issues arise.  People are also used to thinking on 0 to 100 scales, so Celsius is an acceptable use of a derived unit.  It's important to define the unit in the "Temperature" message, so that there will be no confusion with one person interpreting the message using Kelvin and another using Celsuis.  We don't want to end up with negative Kelvin temperatures on our robots!  (Probably. http://en.wikipedia.org/wiki/Negative_temperature#Lasers)

Another important point is that many of the rosbag tools will assume that all messages with the same md5 sum are interchangeable.  The most important example of this is rosbag migration (http://ros.org/wiki/rosbag/migration).  This uses the md5 sum in order to migrate ALL messages and topics matching that md5 sum in the rules to a new message.  So if you wanted to add a "static vs dynamic" constant to the FluidPressure message and trigger a migration - you will have converted all your logged temperatures, illuminances into fluid pressures!  The way the md5 sum is calculated (http://www.ros.org/wiki/ROS/Technical%20Overview#Message_serialization_and_msg_MD5_sums) is why each message has a "tempreature"/"illuminance" field instead of a "value" field, so that I can guarantee unique md5 sums between them."

**Comment by dirk-thomas** [comment]
We do not want to generate more _generic_ message type. There is a lot of value to use a specific semantic type for different use cases and that is why we recommend people to create custom types.

The referenced message from `jsk_pcl_ros` is actually a very bad example. You should not name it `Int32Stamped` but give it a semantically valuable name instead, e.g. `PredectionError`. Otherwise you can feed a `Int32Stamped` message coming from your prediction error publisher to a completely unrelated subscriber reading a `Int32Stamped` but with a very different semantic meaning.

**Comment by csherstan** [comment]
Thanks, that was really helpful.
